# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelop/services/proto/players.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$envelop/services/proto/players.proto\x12\x0c\x65nvelop.grpc\x1a\x1bgoogle/protobuf/empty.proto\"\x16\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\"3\n\nPlayerList\x12%\n\x07players\x18\x01 \x03(\x0b\x32\x14.envelop.grpc.Player2\x8f\x01\n\x07Players\x12?\n\x0bListPlayers\x12\x16.google.protobuf.Empty\x1a\x18.envelop.grpc.PlayerList\x12\x43\n\rStreamPlayers\x12\x16.google.protobuf.Empty\x1a\x18.envelop.grpc.PlayerList0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelop.services.proto.players_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYER']._serialized_start=83
  _globals['_PLAYER']._serialized_end=105
  _globals['_PLAYERLIST']._serialized_start=107
  _globals['_PLAYERLIST']._serialized_end=158
  _globals['_PLAYERS']._serialized_start=161
  _globals['_PLAYERS']._serialized_end=304
# @@protoc_insertion_point(module_scope)
