# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from envelop.services.proto import players_pb2 as envelop_dot_services_dot_proto_dot_players__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class PlayersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListPlayers = channel.unary_unary(
                '/envelop.grpc.Players/ListPlayers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.FromString,
                )
        self.StreamPlayers = channel.unary_stream(
                '/envelop.grpc.Players/StreamPlayers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.FromString,
                )


class PlayersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlayers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.SerializeToString,
            ),
            'StreamPlayers': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlayers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'envelop.grpc.Players', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Players(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/envelop.grpc.Players/ListPlayers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/envelop.grpc.Players/StreamPlayers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            envelop_dot_services_dot_proto_dot_players__pb2.PlayerList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
