# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelop/services/proto/process.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$envelop/services/proto/process.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n\x07\x43ommand\x12\r\n\x05value\x18\x01 \x01(\t\"O\n\x03Log\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x03 \x01(\t2i\n\x07Process\x12\x30\n\x0cWriteCommand\x12\x08.Command\x1a\x16.google.protobuf.Empty\x12,\n\nStreamLogs\x12\x16.google.protobuf.Empty\x1a\x04.Log0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelop.services.proto.process_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMAND']._serialized_start=102
  _globals['_COMMAND']._serialized_end=126
  _globals['_LOG']._serialized_start=128
  _globals['_LOG']._serialized_end=207
  _globals['_PROCESS']._serialized_start=209
  _globals['_PROCESS']._serialized_end=314
# @@protoc_insertion_point(module_scope)
