# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelop/services/proto/rcon.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!envelop/services/proto/rcon.proto\"\x1c\n\x0bRconCommand\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\x0cRconResponse\x12\r\n\x05value\x18\x01 \x01(\t22\n\x04Rcon\x12*\n\x0bSendCommand\x12\x0c.RconCommand\x1a\r.RconResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'envelop.services.proto.rcon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RCONCOMMAND']._serialized_start=37
  _globals['_RCONCOMMAND']._serialized_end=65
  _globals['_RCONRESPONSE']._serialized_start=67
  _globals['_RCONRESPONSE']._serialized_end=96
  _globals['_RCON']._serialized_start=98
  _globals['_RCON']._serialized_end=148
# @@protoc_insertion_point(module_scope)
