// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: rcon.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RconClient is the client API for Rcon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RconClient interface {
	SendCommand(ctx context.Context, in *RconCommand, opts ...grpc.CallOption) (*RconResponse, error)
}

type rconClient struct {
	cc grpc.ClientConnInterface
}

func NewRconClient(cc grpc.ClientConnInterface) RconClient {
	return &rconClient{cc}
}

func (c *rconClient) SendCommand(ctx context.Context, in *RconCommand, opts ...grpc.CallOption) (*RconResponse, error) {
	out := new(RconResponse)
	err := c.cc.Invoke(ctx, "/envelop.Rcon/SendCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RconServer is the server API for Rcon service.
// All implementations must embed UnimplementedRconServer
// for forward compatibility
type RconServer interface {
	SendCommand(context.Context, *RconCommand) (*RconResponse, error)
	mustEmbedUnimplementedRconServer()
}

// UnimplementedRconServer must be embedded to have forward compatible implementations.
type UnimplementedRconServer struct {
}

func (UnimplementedRconServer) SendCommand(context.Context, *RconCommand) (*RconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedRconServer) mustEmbedUnimplementedRconServer() {}

// UnsafeRconServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RconServer will
// result in compilation errors.
type UnsafeRconServer interface {
	mustEmbedUnimplementedRconServer()
}

func RegisterRconServer(s grpc.ServiceRegistrar, srv RconServer) {
	s.RegisterService(&Rcon_ServiceDesc, srv)
}

func _Rcon_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RconCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RconServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/envelop.Rcon/SendCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RconServer).SendCommand(ctx, req.(*RconCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// Rcon_ServiceDesc is the grpc.ServiceDesc for Rcon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rcon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "envelop.Rcon",
	HandlerType: (*RconServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _Rcon_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcon.proto",
}
