// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: steammessages_offline.steamclient.proto

package steampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OfflineClient is the client API for Offline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfflineClient interface {
	GetOfflineLogonTicket(ctx context.Context, in *COffline_GetOfflineLogonTicket_Request, opts ...grpc.CallOption) (*COffline_GetOfflineLogonTicket_Response, error)
	GetUnsignedOfflineLogonTicket(ctx context.Context, in *COffline_GetUnsignedOfflineLogonTicket_Request, opts ...grpc.CallOption) (*COffline_GetUnsignedOfflineLogonTicket_Response, error)
}

type offlineClient struct {
	cc grpc.ClientConnInterface
}

func NewOfflineClient(cc grpc.ClientConnInterface) OfflineClient {
	return &offlineClient{cc}
}

func (c *offlineClient) GetOfflineLogonTicket(ctx context.Context, in *COffline_GetOfflineLogonTicket_Request, opts ...grpc.CallOption) (*COffline_GetOfflineLogonTicket_Response, error) {
	out := new(COffline_GetOfflineLogonTicket_Response)
	err := c.cc.Invoke(ctx, "/Offline/GetOfflineLogonTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offlineClient) GetUnsignedOfflineLogonTicket(ctx context.Context, in *COffline_GetUnsignedOfflineLogonTicket_Request, opts ...grpc.CallOption) (*COffline_GetUnsignedOfflineLogonTicket_Response, error) {
	out := new(COffline_GetUnsignedOfflineLogonTicket_Response)
	err := c.cc.Invoke(ctx, "/Offline/GetUnsignedOfflineLogonTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfflineServer is the server API for Offline service.
// All implementations must embed UnimplementedOfflineServer
// for forward compatibility
type OfflineServer interface {
	GetOfflineLogonTicket(context.Context, *COffline_GetOfflineLogonTicket_Request) (*COffline_GetOfflineLogonTicket_Response, error)
	GetUnsignedOfflineLogonTicket(context.Context, *COffline_GetUnsignedOfflineLogonTicket_Request) (*COffline_GetUnsignedOfflineLogonTicket_Response, error)
	mustEmbedUnimplementedOfflineServer()
}

// UnimplementedOfflineServer must be embedded to have forward compatible implementations.
type UnimplementedOfflineServer struct {
}

func (UnimplementedOfflineServer) GetOfflineLogonTicket(context.Context, *COffline_GetOfflineLogonTicket_Request) (*COffline_GetOfflineLogonTicket_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOfflineLogonTicket not implemented")
}
func (UnimplementedOfflineServer) GetUnsignedOfflineLogonTicket(context.Context, *COffline_GetUnsignedOfflineLogonTicket_Request) (*COffline_GetUnsignedOfflineLogonTicket_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnsignedOfflineLogonTicket not implemented")
}
func (UnimplementedOfflineServer) mustEmbedUnimplementedOfflineServer() {}

// UnsafeOfflineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfflineServer will
// result in compilation errors.
type UnsafeOfflineServer interface {
	mustEmbedUnimplementedOfflineServer()
}

func RegisterOfflineServer(s grpc.ServiceRegistrar, srv OfflineServer) {
	s.RegisterService(&Offline_ServiceDesc, srv)
}

func _Offline_GetOfflineLogonTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(COffline_GetOfflineLogonTicket_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineServer).GetOfflineLogonTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Offline/GetOfflineLogonTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineServer).GetOfflineLogonTicket(ctx, req.(*COffline_GetOfflineLogonTicket_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Offline_GetUnsignedOfflineLogonTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(COffline_GetUnsignedOfflineLogonTicket_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfflineServer).GetUnsignedOfflineLogonTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Offline/GetUnsignedOfflineLogonTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfflineServer).GetUnsignedOfflineLogonTicket(ctx, req.(*COffline_GetUnsignedOfflineLogonTicket_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Offline_ServiceDesc is the grpc.ServiceDesc for Offline service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Offline_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Offline",
	HandlerType: (*OfflineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOfflineLogonTicket",
			Handler:    _Offline_GetOfflineLogonTicket_Handler,
		},
		{
			MethodName: "GetUnsignedOfflineLogonTicket",
			Handler:    _Offline_GetUnsignedOfflineLogonTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steammessages_offline.steamclient.proto",
}
