// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: webuimessages_sharedjscontext.proto

package steampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SharedJSContextClient is the client API for SharedJSContext service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharedJSContextClient interface {
	GetDesiredSteamUIWindows(ctx context.Context, in *CSharedJSContext_GetDesiredSteamUIWindows_Request, opts ...grpc.CallOption) (*CSharedJSContext_GetDesiredSteamUIWindows_Response, error)
}

type sharedJSContextClient struct {
	cc grpc.ClientConnInterface
}

func NewSharedJSContextClient(cc grpc.ClientConnInterface) SharedJSContextClient {
	return &sharedJSContextClient{cc}
}

func (c *sharedJSContextClient) GetDesiredSteamUIWindows(ctx context.Context, in *CSharedJSContext_GetDesiredSteamUIWindows_Request, opts ...grpc.CallOption) (*CSharedJSContext_GetDesiredSteamUIWindows_Response, error) {
	out := new(CSharedJSContext_GetDesiredSteamUIWindows_Response)
	err := c.cc.Invoke(ctx, "/SharedJSContext/GetDesiredSteamUIWindows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharedJSContextServer is the server API for SharedJSContext service.
// All implementations must embed UnimplementedSharedJSContextServer
// for forward compatibility
type SharedJSContextServer interface {
	GetDesiredSteamUIWindows(context.Context, *CSharedJSContext_GetDesiredSteamUIWindows_Request) (*CSharedJSContext_GetDesiredSteamUIWindows_Response, error)
	mustEmbedUnimplementedSharedJSContextServer()
}

// UnimplementedSharedJSContextServer must be embedded to have forward compatible implementations.
type UnimplementedSharedJSContextServer struct {
}

func (UnimplementedSharedJSContextServer) GetDesiredSteamUIWindows(context.Context, *CSharedJSContext_GetDesiredSteamUIWindows_Request) (*CSharedJSContext_GetDesiredSteamUIWindows_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDesiredSteamUIWindows not implemented")
}
func (UnimplementedSharedJSContextServer) mustEmbedUnimplementedSharedJSContextServer() {}

// UnsafeSharedJSContextServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharedJSContextServer will
// result in compilation errors.
type UnsafeSharedJSContextServer interface {
	mustEmbedUnimplementedSharedJSContextServer()
}

func RegisterSharedJSContextServer(s grpc.ServiceRegistrar, srv SharedJSContextServer) {
	s.RegisterService(&SharedJSContext_ServiceDesc, srv)
}

func _SharedJSContext_GetDesiredSteamUIWindows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CSharedJSContext_GetDesiredSteamUIWindows_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedJSContextServer).GetDesiredSteamUIWindows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SharedJSContext/GetDesiredSteamUIWindows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedJSContextServer).GetDesiredSteamUIWindows(ctx, req.(*CSharedJSContext_GetDesiredSteamUIWindows_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SharedJSContext_ServiceDesc is the grpc.ServiceDesc for SharedJSContext service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharedJSContext_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SharedJSContext",
	HandlerType: (*SharedJSContextServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDesiredSteamUIWindows",
			Handler:    _SharedJSContext_GetDesiredSteamUIWindows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webuimessages_sharedjscontext.proto",
}
