process:
  command: >-
    {{ .Exe }}
    -nographics
    -batchmode
    -name "My server"
    -port 2456
    -world "Dedicated"
    -password "secret"
    -savedir {{ .Destination }}/envelop_world
    -public 0
  environment:
    SteamAppId: "892970"
  graceful:
    type: cmd
    timeout: 30
    options:
      cmd: stop

logging:
  - type: default
    options:
      format: text
      level: 12

modules:
  - uses: envelop.core
